import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, dirname, relative } from "node:path";

const WS_URL = process.env.WS_URL || "ws://localhost:8787";
const target = process.env.TARGET || "all"; // "user" | "ext" | "all"
const manifest = JSON.parse(readFileSync("client/extension/manifest.json", "utf8"));
const VERSION = manifest.version;
const RELEASES_API = process.env.RELEASES_API || "https://api.github.com/repos/AviouslyAvi/Watch-Party/releases/latest";
const RELEASES_URL = process.env.RELEASES_URL || "https://github.com/AviouslyAvi/Watch-Party/releases/latest";
const LANDING_URL = process.env.LANDING_URL || "https://watch-party.pages.dev";

mkdirSync("dist", { recursive: true });

// ---------------------- Generated notification sound ----------------------
// A short two-note WAV chime, ~480ms. Written to a generated TS module as a
// data URL so both the userscript and extension bundles ship it the same way.
const SOUND_TS_PATH = "client/extension/_sound.generated.ts";
function ensureGeneratedSound() {
  if (existsSync(SOUND_TS_PATH)) return;
  const wav = synthesizeChimeWav();
  const b64 = Buffer.from(wav).toString("base64");
  writeFileSync(SOUND_TS_PATH, `// Auto-generated by build.mjs — do not edit by hand.\nexport const NOTIFY_SOUND_DATA_URL = "data:audio/wav;base64,${b64}";\n`);
  console.log(`✓ ${SOUND_TS_PATH} (${wav.length} bytes WAV)`);
}
function synthesizeChimeWav() {
  // 22050 Hz, 16-bit mono. Two soft notes (E5 then A5) with short attack + decay.
  const sampleRate = 22050;
  const durations = [0.18, 0.30]; // seconds per note
  const freqs = [659.25, 880.0];  // E5, A5
  const samplesPerNote = durations.map((d) => Math.floor(d * sampleRate));
  const totalSamples = samplesPerNote.reduce((a, b) => a + b, 0);

  const pcm = new Int16Array(totalSamples);
  let cursor = 0;
  for (let n = 0; n < freqs.length; n++) {
    const N = samplesPerNote[n];
    const f = freqs[n];
    for (let i = 0; i < N; i++) {
      const t = i / sampleRate;
      // Soft attack-release envelope.
      const attack = Math.min(1, t / 0.012);
      const release = Math.min(1, (N - i) / (sampleRate * 0.06));
      const env = attack * release;
      // Sine + small sub-octave for warmth.
      const v = Math.sin(2 * Math.PI * f * t) * 0.75 + Math.sin(2 * Math.PI * (f / 2) * t) * 0.18;
      pcm[cursor + i] = Math.round(v * env * 0.42 * 0x7fff);
    }
    cursor += N;
  }

  const byteLength = pcm.byteLength;
  const buf = Buffer.alloc(44 + byteLength);
  // RIFF header
  buf.write("RIFF", 0);
  buf.writeUInt32LE(36 + byteLength, 4);
  buf.write("WAVE", 8);
  buf.write("fmt ", 12);
  buf.writeUInt32LE(16, 16);          // fmt chunk size
  buf.writeUInt16LE(1, 20);            // PCM
  buf.writeUInt16LE(1, 22);            // mono
  buf.writeUInt32LE(sampleRate, 24);
  buf.writeUInt32LE(sampleRate * 2, 28); // byte rate
  buf.writeUInt16LE(2, 32);            // block align
  buf.writeUInt16LE(16, 34);           // bits per sample
  buf.write("data", 36);
  buf.writeUInt32LE(byteLength, 40);
  Buffer.from(pcm.buffer, pcm.byteOffset, pcm.byteLength).copy(buf, 44);
  return buf;
}
ensureGeneratedSound();

// ---------------------- esbuild bundles ----------------------
const sharedDefines = {
  WS_URL: JSON.stringify(WS_URL),
  VERSION: JSON.stringify(VERSION),
  RELEASES_API: JSON.stringify(RELEASES_API),
  RELEASES_URL: JSON.stringify(RELEASES_URL),
  LANDING_URL: JSON.stringify(LANDING_URL),
};

async function bundleText(entry) {
  const result = await build({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    target: "es2020",
    define: sharedDefines,
    loader: { ".css": "text", ".ttf": "binary", ".otf": "binary", ".wav": "binary" },
    write: false,
    legalComments: "none",
  });
  return result.outputFiles[0].text;
}

function buildUserscript(js) {
  const banner = readFileSync("client/userscript/banner.txt", "utf8");
  writeFileSync("dist/avious-party.user.js", banner + "\n" + js);
  console.log(`✓ dist/avious-party.user.js (WS_URL=${WS_URL})`);
}

function copyDir(srcDir, destDir) {
  if (!existsSync(srcDir)) return;
  for (const name of readdirSync(srcDir)) {
    const src = join(srcDir, name);
    const dest = join(destDir, name);
    if (statSync(src).isDirectory()) {
      mkdirSync(dest, { recursive: true });
      copyDir(src, dest);
    } else {
      mkdirSync(dirname(dest), { recursive: true });
      copyFileSync(src, dest);
    }
  }
}

async function buildExtension(contentJs) {
  mkdirSync("dist/extension", { recursive: true });
  // Content script
  writeFileSync("dist/extension/content.js", contentJs);
  // Service worker
  const bgJs = await bundleText("client/extension/background.ts");
  writeFileSync("dist/extension/background.js", bgJs);
  // Popup
  const popupJs = await bundleText("client/extension/popup/popup.ts");
  mkdirSync("dist/extension/popup", { recursive: true });
  writeFileSync("dist/extension/popup/popup.js", popupJs);
  copyFileSync("client/extension/popup/popup.html", "dist/extension/popup/popup.html");
  // Assets (fonts, etc.) and styles (popup.css references font paths)
  mkdirSync("dist/extension/assets", { recursive: true });
  copyDir("client/extension/assets", "dist/extension/assets");
  mkdirSync("dist/extension/styles", { recursive: true });
  copyDir("client/extension/styles", "dist/extension/styles");
  // Manifest
  copyFileSync("client/extension/manifest.json", "dist/extension/manifest.json");
  console.log(`✓ dist/extension/ (WS_URL=${WS_URL})`);
}

const contentJs = await bundleText("client/userscript/main.ts");
if (target === "user" || target === "all") buildUserscript(contentJs);
if (target === "ext" || target === "all") await buildExtension(contentJs);

// Silence unused import lint in editors during dev.
void relative;
